name: ci-cd
on:
 push:
  branches: [main]
  paths-ignore: 
    - 'kubernetes/deployment.yaml'

 pull_request: 
  branches: [main]


jobs:
  test:
    name: Unit-Testing
    runs-on: ubuntu-latest
    steps:
      - name: Code-Checkout
        uses: actions/checkout@v4

      - name: set up node js
        uses: actions/setup-node@v4
        with: 
         version: 'node-20'
         cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Test Cases
        run: npm test

  lint:
     name: Static-Code-Analysis
     runs-on: ubuntu-latest
     steps:
       - name: Code-Checkout
         uses: actions/checkout@v4
 
       - name: set up node js
         uses: actions/setup-node@v4
         with: 
          version: 'node-20'
          cache: 'npm'
 
       - name: Install Dependencies
         run: npm ci
 
       - name: Run Static Code Analysis
         run: npm run lint

  Build:
     name: Build-Node-js-Application
     needs: [test, lint]
     runs-on: ubuntu-latest
     steps:
       - name: Code-Checkout
         uses: actions/checkout@v4
 
       - name: set up node js
         uses: actions/setup-node@v4
         with: 
          version: 'node-20'
          cache: 'npm'
 
       - name: Install Dependencies
         run: npm ci
 
       - name: Build-Node-js-Application
         run: npm run build

       - name: Upload-Build-Artifact
         uses:  actions/upload-artifact@v4
         with:
            name: Build Artifact
            path: dist/

  Docker:
     name: Build-and-Push-the-Docker-Image
     needs: [Build]
     runs-on: ubuntu-latest
     env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      
     steps:
       - name: Code-Checkout
         uses: actions/checkout@v4

       - name: Download-Build-Artifact
         uses: actions/download-artifact@v4
         with:
            name: Build Artifact
            path: dist/
      
       - name: Set-Up-Docker
         uses: docker/setup-buildx-action@v3

       - name: Login-to=Github-Container-Registry
         uses: docker/setup-buildx-action@v3
         with: 
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      
      




 


